[package]
name = "meide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hash-rings = "1.1.0"
tokio = { version = "1.32.0", features = ["full"] }
